# Generated by Django 2.1.1 on 2018-09-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategoria', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(default='2018-09-10')),
            ],
        ),
    ]
