# Generated by Django 2.1.1 on 2018-09-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_producto_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='numExist',
            field=models.IntegerField(default=0),
        ),
    ]
